### ISSUE TITLE
Update command prior to release

### ISSUE THREAD

**Issue by AshciR** [rick1e/group-chat-digest#48]
Before we release, let's: 
- Remove the `/replay` command
- Update `/start` command with instructions on how to use the bot, minor privacy notes, and legalities.

**Comment by rick1e** [comment]
Update `/start` command to perform the primary summary action.
Results should be in the paragraph format

Update `/gist` command to return the bullet points

Additional information on how to use the bot should be in the `/help` command

Add a unit tests for the changes!!
